stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: gradle:5.2.1-jre8-alpine
          shellScript: |-
            gradle clean assemble
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: plc-controller:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
